LoginWebForm/Controllers/DepartmentController.cs
using LoginWebForm.Areas.Identity.Data;
using LoginWebForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoginWebForm.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext _DB;
        public DepartmentController(ApplicationDbContext Db)
        {
            _DB = Db;
        }
        public IActionResult DepartmentList(string SearchText = "")
        {
            List<Department> emp;
            if (SearchText != "" & SearchText != null)
            {
                emp = _DB.tbl_Department
                    .Where(e => e.Name.Contains(SearchText)).ToList();
            }
            else

                emp = _DB.tbl_Department.ToList();

            return View(emp);
            //List<Department> dep;
            //dep = _DB.tbl_Department.ToList();
            //return View(dep);
            //return View();
        }
        
        [HttpGet]
        public IActionResult Create(Department obj)
        {
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddDepartment(Department obj)
        {
            try
            {
                if (obj.ID == 0)
                {
                    _DB.tbl_Department.Add(obj);
                    await _DB.SaveChangesAsync();

                }
                else
                {
                    _DB.Entry(obj).State = EntityState.Modified;
                    await _DB.SaveChangesAsync();
                }
                return RedirectToAction("DepartmentList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("DepartmentList");

            }
        }

        public IActionResult DepartmentDetail(int Id)
        {
            Department emp = _DB.tbl_Department.Where(x => x.ID == Id).FirstOrDefault();
            return View(emp);
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Department obj = _DB.tbl_Department.Where(p => p.ID == Id).FirstOrDefault();
            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(Department obj)
        {
            _DB.Attach(obj);
            _DB.Entry(obj).State = EntityState.Deleted;
            _DB.SaveChanges();
            return RedirectToAction("DepartmentList");
        }
    }
}

LoginWebForm/Controllers/DesignationController.cs
using LoginWebForm.Areas.Identity.Data;
using LoginWebForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoginWebForm.Controllers
{
    [Authorize]
    public class DesignationController : Controller
    {
        private readonly ApplicationDbContext _DB;
        public DesignationController(ApplicationDbContext Db)
        {
            _DB = Db;
        }
        public IActionResult DesignatonList()
        {
            List<Designation> dep;
            dep = _DB.tbl_Designation.ToList();
            return View(dep);
            return View();
        }


        [HttpGet]
        public IActionResult Create(Designation obj)
        {
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddDesignaiton(Designation obj)
        {
            try
            {
                if (obj.ID == 0)
                {
                    _DB.tbl_Designation.Add(obj);
                    await _DB.SaveChangesAsync();

                }
                else
                {
                    _DB.Entry(obj).State = EntityState.Modified;
                    await _DB.SaveChangesAsync();
                }
                return RedirectToAction("DesignatonList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("DesignatonList");

            }
        }

        public IActionResult DesignationDetail(int Id)
        {
            Designation emp = _DB.tbl_Designation.Where(x => x.ID == Id).FirstOrDefault();
            return View(emp);
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Designation obj = _DB.tbl_Designation.Where(p => p.ID == Id).FirstOrDefault();
            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(Designation obj)
        {
            _DB.Attach(obj);
            _DB.Entry(obj).State = EntityState.Deleted;
            _DB.SaveChanges();
            return RedirectToAction("DesignatonList");
        }
    }
}

LoginWebForm/Controllers/EmployeeController.cs
using LoginWebForm.Areas.Identity.Data;
using LoginWebForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoginWebForm.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _DB;
        private readonly IWebHostEnvironment _webHost;
        public EmployeeController(ApplicationDbContext Db, IWebHostEnvironment webHost)
        {
            _DB = Db;
            this._webHost = webHost;
        }

        public IActionResult EmployeeList()
        {
            try
            {
                var stdlist = from a in _DB.tbl_Employee
                              join b in _DB.tbl_Department
                              on a.DepID equals b.ID
                              join c in _DB.tbl_Designation
                              on a.DesID equals c.ID
                              into Emp
                              from c in Emp.DefaultIfEmpty()
                              select new Employee
                              {
                                  ID = a.ID,
                                  DepID = a.DepID,
                                  DesID = a.DesID,
                                  Name = a.Name,
                                  FName = a.FName,
                                  Email = a.Email,
                                  Contact=a.Contact,
                                  Date = a.Date,
                                  Image = a.Image,
                                  Department = b == null ? null : b.Name,
                                  Designation = c == null ? null : c.Name,

                              };

                return View(stdlist);
            }
            catch (Exception ex)
            {

                return View();
            }
            //List<Employee> emp;
            //if (SearchText != "" & SearchText != null)
            //{
            //    emp = _DB.tbl_Employee
            //        .Where(e => e.Name.Contains(SearchText)).ToList();
            //}
            //else

            //    emp = _DB.tbl_Employee.ToList();

            //return View(emp);
        }

        [HttpGet]
        public IActionResult Create(Employee obj)
        {
            loadDEP();
            loadDES();
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> AddEmployee(Employee obj, IFormFile images)
        {
            try
            {
                string uniquefilename = string.Empty;
                if (images != null)
                {
                    string uploadsfolder = Path.Combine(_webHost.WebRootPath, "images");
                    uniquefilename = Guid.NewGuid().ToString() + "_" + images.FileName;
                    string filePath = Path.Combine(uploadsfolder, uniquefilename);
                    images.CopyTo(new FileStream(filePath, FileMode.Create));
                    obj.Image = uniquefilename;
                }
                if (obj.ID == 0)
                {
                    _DB.tbl_Employee.Add(obj);
                    await _DB.SaveChangesAsync();
                }
                else
                {
                    _DB.Entry(obj).State = EntityState.Modified;
                    await _DB.SaveChangesAsync();
                }
                return RedirectToAction("EmployeeList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("EmployeeList");

            }
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Employee obj = _DB.tbl_Employee.Where(p => p.ID == Id).FirstOrDefault();
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Employee obj)
        {
            _DB.Attach(obj);
            _DB.Entry(obj).State = EntityState.Deleted;
            _DB.SaveChanges();
            return RedirectToAction("EmployeeList");
        }



        public IActionResult EmployeeDetail(int Id)
        {
            Employee emp = _DB.tbl_Employee.Where(x => x.ID == Id).FirstOrDefault();
            return View(emp);
        }



        private void loadDEP()
        {
            try
            {
                List<Department> deplist = new List<Department>();
                deplist = _DB.tbl_Department.ToList();
                deplist.Insert(0, new Department { ID = 0, Name = "Please Select" });
                ViewBag.DepList = deplist;

            }
            catch (Exception ex)
            {

                throw;
            }
        }


        private void loadDES()
        {
            try
            {
                List<Designation> deslist = new List<Designation>();
                deslist = _DB.tbl_Designation.ToList();
                deslist.Insert(0, new Designation { ID = 0, Name = "Please Select" });
                ViewBag.DesList = deslist;

            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

LoginWebForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoginWebForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginWebForm.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LoginWebForm</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="DepartmentList">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Designation" asp-action="DesignatonList">Designation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeList">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attandence" asp-action="AttandenceList">Attandence</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LoginWebForm - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>